### ISSUE TITLE
DESCRIPTION format is incompatible with devtools package

### ISSUE THREAD

**Issue by MelissaWillKill** [robjhyndman/MEFM-package#6]
When installing the MEFM-package through devtools, I was thrown an error:

> Error read.dcf(path) : Found continuation line starting ' The package requi ...' at begin of record.

It seems this error isn't specific to the MEFM-package. See: [Issue 1900](https://github.com/r-lib/devtools/issues/1900).

When installing through [githubinstall](https://cran.r-project.org/web/packages/githubinstall/githubinstall.pdf), all runs smoothly:
`install.packages("githubinstall")`
`library(githubinstall)`
`gh_install_packages("MEFM-package")`
`library(MEFM)`

**Comment by ProfessorSugar** [comment]
Neither githubinstall and devtools works for me. Same error was thrown:
> Error read.dcf(path) : Found continuation line starting ' The package requi ...' at begin of record.

**Comment by robjhyndman** [comment]
It should work now with https://github.com/robjhyndman/MEFM-package/commit/48346a63fc06722ab2f7e08983b0c6decf6a5419
